import { Link, useRoute } from "wouter";
import { ArrowLeft, ArrowUpRight, Check } from "lucide-react";

/** NOVA FORMA style: project case study as a quiet, cinematic editorial spread. */
const data: Record<string,{name:string;type:string;location:string;area:string;year:string;image:string;intro:string;concept:string;materials:string[]}> = {
  "sosnovy-sklon": {name:"Сосновый склон",type:"Частный дом",location:"Московская область",area:"640 м²",year:"2024",image:"/manus-storage/nova-forma-hero_32fadf23.png",intro:"Резиденция, встроенная в сосновый ландшафт и рассчитанная на тихую жизнь за городом.",concept:"Задача проекта — создать дом, который не конкурирует с лесом, а продолжает его. Панорамное остекление собирает виды в живые картины, внутренний двор защищает приватность, а тяжелый бетонный объем работает как спокойное основание для теплых деревянных интерьеров.",materials:["Архитектурный бетон","Дуб","Натуральный камень","Панорамное остекление"]},
  "liniya-gorizonta": {name:"Линия горизонта",type:"Частная резиденция",location:"Истринский район",area:"420 м²",year:"2023",image:"/manus-storage/nova-forma-interior_0b4b98b6.png",intro:"Дом, собранный вокруг вида: видовая терраса, скрытая инженерия и энергоэффективный фасад.",concept:"Лаконичная горизонталь здания раскрывается к ландшафту. Внутренние маршруты проходят вдоль света, а инженерные решения спрятаны так, чтобы архитектура оставалась чистой и цельной.",materials:["Клинкер","Лиственница","Алюминий","Бетон"]},
  "port": {name:"Пространство «Порт»",type:"Офис и шоурум",location:"Санкт-Петербург",area:"1 850 м²",year:"2024",image:"/manus-storage/nova-forma-project_3f402da0.png",intro:"Коммерческое пространство, где выставочная функция соединяется с ежедневной работой команды.",concept:"Открытая планировка разделена не стенами, а светом, материалами и ритмом потолочных конструкций. Переговорные, шоурум и рабочие зоны складываются в единый сценарий движения.",materials:["Металл","Стекло","Бетон","Натуральный камень"]},
  "severny-sad": {name:"Северный сад",type:"Бутик-отель",location:"Ленинградская область",area:"3 200 м²",year:"2022",image:"/manus-storage/nova-forma-materials_2ac250db.png",intro:"Бутик-отель на 28 номеров с рестораном, spa-зоной и ландшафтом для замедления.",concept:"Проект строится на контрасте северного климата и теплого гостеприимства. Камень и дерево задают тактильный ритм интерьеров, а благоустроенная территория становится продолжением общественных пространств.",materials:["Дерево","Камень","Штукатурка","Стекло"]}
};
export default function ProjectDetail(){ const [,params]=useRoute("/projects/:slug"); const p=data[params?.slug||""]||data["sosnovy-sklon"]; return <div className="site project-detail"><header className="header"><Link href="/" className="back"><ArrowLeft size={16}/> Все проекты</Link><span className="detail-logo">NOVA FORMA <i>Architecture & Construction</i></span><a href="/#contact" className="header-cta">Обсудить проект <ArrowUpRight size={15}/></a></header><main><section className="detail-hero"><img src={p.image} alt={p.name}/><div className="hero-shade"/><div className="detail-title"><span>Проект · {p.year}</span><h1>{p.name}</h1><p>{p.intro}</p></div></section><section className="case-grid"><div><span className="case-kicker">01 / Концепция</span><h2>Архитектура<br/><em>как продолжение</em></h2></div><div className="case-text"><p>{p.concept}</p><a className="text-link" href="/#contact">Обсудить похожую задачу <ArrowUpRight size={16}/></a></div></section><section className="case-facts"><div className="facts-head"><span>02 / Характеристики</span><h2>Точные решения<br/><em>для жизни</em></h2></div><div className="facts"><div><span>Локация</span><strong>{p.location}</strong></div><div><span>Площадь</span><strong>{p.area}</strong></div><div><span>Завершение</span><strong>{p.year}</strong></div><div><span>Тип объекта</span><strong>{p.type}</strong></div></div></section><section className="case-materials"><div className="material-copy"><span className="case-kicker">03 / Материалы</span><h2>Материалы,<br/><em>которые стареют красиво</em></h2><div className="detail-material-list">{p.materials.map((m,i)=><div key={m}><span>0{i+1}</span>{m}<Check size={14}/></div>)}</div></div><img src="/manus-storage/nova-forma-materials_2ac250db.png" alt="Материалы проекта"/></section></main><footer><div className="footer-brand"><span className="detail-logo">NOVA FORMA</span><p>Создаем пространства,<br/>которые остаются.</p></div><div className="footer-contact"><span>Москва · Санкт-Петербург</span><a href="mailto:hello@novaforma.example">hello@novaforma.example</a></div><div className="footer-bottom"><span>© 2024 NOVA FORMA</span><Link href="/">Вернуться на главную</Link></div></footer></div> }
